// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/messages-home/MessagesHome.tsx": () => import("../components/mockups/messages-home/MessagesHome.tsx"),
  "./components/mockups/messages-home/StudentHomeWithMessages.tsx": () => import("../components/mockups/messages-home/StudentHomeWithMessages.tsx"),
  "./components/mockups/audio/StudentAudio.tsx": () => import("../components/mockups/audio/StudentAudio.tsx"),
  "./components/mockups/palettes/NavyGold.tsx": () => import("../components/mockups/palettes/NavyGold.tsx"),
  "./components/mockups/palettes/NavyLavender.tsx": () => import("../components/mockups/palettes/NavyLavender.tsx"),
  "./components/mockups/palettes/NavyRose.tsx": () => import("../components/mockups/palettes/NavyRose.tsx"),
  "./components/mockups/palettes/NavyTeal.tsx": () => import("../components/mockups/palettes/NavyTeal.tsx"),
  "./components/mockups/palettes/PaletteDawn.tsx": () => import("../components/mockups/palettes/PaletteDawn.tsx"),
  "./components/mockups/palettes/PaletteHoney.tsx": () => import("../components/mockups/palettes/PaletteHoney.tsx"),
  "./components/mockups/palettes/PaletteLavender.tsx": () => import("../components/mockups/palettes/PaletteLavender.tsx"),
  "./components/mockups/palettes/PaletteNavy.tsx": () => import("../components/mockups/palettes/PaletteNavy.tsx"),
  "./components/mockups/palettes/PaletteParchment.tsx": () => import("../components/mockups/palettes/PaletteParchment.tsx"),
  "./components/mockups/palettes/PaletteRose.tsx": () => import("../components/mockups/palettes/PaletteRose.tsx"),
  "./components/mockups/student-full/StudentFullPage.tsx": () => import("../components/mockups/student-full/StudentFullPage.tsx")
};
